name = "AntibodyMethodsDoseResponse"
uuid = "69c61766-33fa-4661-b145-6c090ebe636b"
authors = ["Dominik Tschimmel <dominik.tschimmel.contact@gmail.com> and contributors"]
version = "0.2.5"

[deps]
AdaptiveDensityApproximation = "56a9bb0d-c37d-45c9-8e6c-6c1c1baae5c6"
FittingObjectiveFunctions = "935aaf18-14c7-4785-87e9-38cf17c1e7c1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
